name: build and deploy
on:
  push:
    branches:
      - master
jobs:
  test:
    run-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: install dependencies
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.9'
          channel: 'stable'
      - name: check version
        run: flutter --version
