name: Build and Deploy

env:
  flutter_version: "3.3.9"

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Cache Flutter
        uses: actions/cache@v1
        with:
          path: /opt/hostedtoolcache/flutter
          key: flutter-environment-cache-${{ env.flutter_version }}

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: "stable"

      - name: Cache Dependencies
        uses: actions/cache@v1
        with:
          path: ~/.pub-cache
          key: flutter-pubspec-${{ hashFiles('**/pubspec.lock') }}

      - name: Get Packages
        run: flutter pub get

      - name: Run Tests
        run: flutter test

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Cache Flutter
        uses: actions/cache@v1
        with:
          path: /opt/hostedtoolcache/flutter
          key: flutter-environment-cache-${{ env.flutter_version }}

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}
          channel: "stable"

      - name: Cache Dependencies
        uses: actions/cache@v1
        with:
          path: ~/.pub-cache
          key: flutter-pubspec-${{ hashFiles('**/pubspec.lock') }}

      - name: Get Packages
        run: flutter pub get

      - name: Run Tests
        run: flutter build web

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo Deploy...
